"""Hand-written types for ``pyftdi.ftdi`` (pinned ``>=0.57,<0.58``).

Scope is deliberately narrow: only the members ``src/motor/ftdi_link.py``
actually touches. There is deliberately **no** module-level ``__getattr__``:
reaching for an unstubbed member must fail the build rather than silently
resolve to ``Any``.

Signatures were read off the installed source
(``.venv/lib/python3.12/site-packages/pyftdi/ftdi.py``, 0.57.2), not from the
documentation. ``FtdiError`` derives from ``IOError`` (so ``OSError``) there,
which is what lets the transport treat every pyftdi failure as an ``OSError``.
"""

from usb.core import Device

class FtdiError(OSError): ...

class Ftdi:
    LATENCY_MIN: int
    LATENCY_MAX: int
    @classmethod
    def create_from_url(cls, url: str) -> Ftdi: ...
    def open_from_url(self, url: str) -> None: ...
    def open_from_device(self, device: Device, interface: int = 1) -> None: ...
    @property
    def usb_dev(self) -> Device | None: ...
    @property
    def port_index(self) -> int | None: ...
    @classmethod
    def add_custom_vendor(cls, vid: int, vidname: str = "") -> None: ...
    @classmethod
    def add_custom_product(cls, vid: int, pid: int, pidname: str = "") -> None: ...
    def set_baudrate(self, baudrate: int, constrain: bool = True) -> int: ...
    def set_line_property(
        self, bits: int, stopbit: int | float, parity: str, break_: bool = False
    ) -> None: ...
    def set_flowctrl(self, flowctrl: str) -> None: ...
    def set_latency_timer(self, latency: int) -> None: ...
    def purge_buffers(self) -> None: ...
    @property
    def timeouts(self) -> tuple[int, int]: ...
    @timeouts.setter
    def timeouts(self, timeouts: tuple[int, int]) -> None: ...
    def read_data(self, size: int) -> bytes: ...
    def write_data(self, data: bytes | bytearray) -> int: ...
    def close(self, freeze: bool = False) -> None: ...
